import type { Metadata } from "next";
import {Fira_Code, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

export const FiraCode = Fira_Code({
    weight: ['400', '500', '700'], // Specify desired weights
    display: 'swap', // Control font loading behavior
    subsets: ['latin'], // Specify font subsets
    variable: '--font-fira-code', // Optional: CSS variable for easier styling
});

export const metadata: Metadata = {
    title: "АвтоРейлТранс",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${FiraCode.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
